experiment_name: "svm_qkernel_fashion_exp"

dataset:
  name: fashion_mnist
  binary_classes: [3, 8]
  grayscale: true

training:
  batch_size: 256

qkernel:
  n_wires: 6
  n_layers: 2
  rotation: "Y"
  device: "default.qubit"
  gpu_device: "lightning.gpu"
  use_gpu: true
  use_pca: true
  pca_components: 6
  max_samples: 500
  C: 2.0
  kernel_workers: 4

checkpoint:
  save_dir: "checkpoints"
  subdir: "fashion_mnist_svm_qkernel"
